default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        files: src/

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [ --in-place, --remove-all-unused-imports, --remove-duplicate-keys ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        files: src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        files: src/